### ISSUE TITLE
EPiServer v.10 update

### ISSUE THREAD

**Issue by appendix68** [BVNetwork/SqlBlobProvider#1]
Any support for newest EPiServer version soon? :)

**Comment by permagne** [comment]
Package has been submitted to the nuget feed. Should be available real soon

**Comment by evest** [comment]
Available in the feed with version [1.4.2](http://nuget.episerver.com/en/OtherPages/Package/?packageId=EPiCode.SqlBlobProvider&packageVersion=1.4.2)

**Comment by appendix68** [comment]
Awesome, thanks guys!
